[project]
name = "emg2bids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dcm2niix>=1.0.20220715",
    "heudiconv>=1.3.1",
    "ruff>=0.7.2",
]
